#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8600
spring:
  redis:
    database: 0
#    host: 39.107.84.0
    host: localhost
    port: 6379
    password:
  application:
    name: service-oyster
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oyster
    username: oysterwords
    password: oysterwords
    hikari:
      max-lifetime: 20000
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dbem
#    username: root
#    password: one11111
mybatis:
  type-aliases-package: com.example.demo.entity
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config